filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/app-*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      service: shipment-api
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: warning
